name: Generate and Deploy

on:
  push:
    branches: [
      'ci/**'
    ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node_modules cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
          key: yarn-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}

      - name: yarn install
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: build
        env:
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
          RUNTIME_TARGET: ${{ inputs.target }}
        run: |
          yarn build

      # - name: Get Package Version
      #   id: package-version
      #   uses: martinbeentjes/npm-get-version-action@master

      # - name: Tag Package Version
      #   run: git tag v${{ steps.package-version.outputs.current-version }}

      # - name: Create Release Package
      #   uses: montudor/action-zip@v1
      #   with:
      #     args:
      #       zip -qq -r v${{ steps.package-version.outputs.current-version }}.zip
      #       output

      # - name: Upload Latest Release
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: v${{ steps.package-version.outputs.current-version }}.zip
      #     path: v${{ steps.package-version.outputs.current-version }}.zip

      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: v${{ steps.package-version.outputs.current-version }}.zip
      #     asset_name: v${{ steps.package-version.outputs.current-version }}.zip
      #     tag: v${{ steps.package-version.outputs.current-version }}
      #     overwrite: true

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./output
      #     keep_files: true
      #     cname: dsearch.mask.r2d2.to
