name: Generate and Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      enableCache:
        description: 'Enable fetching from cache'
        required: false
        default: true
        type: boolean

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node_modules cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
          key: yarn-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}

      - name: yarn install
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: build
        env:
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
          RUNTIME_TARGET: ${{ inputs.target }}
          RUNTIME_ENABLE_CACHE: ${{ inputs.enableCache }}
        run: |
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
          cname: dsearch.mask.r2d2.to


